logging:
  level:
    com.soon83: debug
    #org.hibernate.type.descriptor.sql: trace

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      #url: jdbc:h2:~/Study/h2/work-management/test;mode=mysql
      jdbc-url: jdbc:h2:tcp://localhost/~/Devtools/h2-database/springboot-kotlin-jpa;mode=mysql
      username: sa
      password:

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  jackson:
    default-property-inclusion: non_null
